name: relive_web3
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs 
  google_fonts: ^2.1.0
  intl: ^0.17.0
  local_storage_stories_api:
    path: packages/local_storage_stories_api
  path_provider: ^2.0.11
  stories_api:
    path: packages/stories_api
  stories_repository:
    path: packages/stories_repository


dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
