// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABF8h4vH67ms9w0nFWQgQh4M-EQnIU8Ss',
    appId: '1:713602982924:web:1c73b1fb541ade78a0ba29',
    messagingSenderId: '713602982924',
    projectId: 'relive-web3',
    authDomain: 'relive-web3.firebaseapp.com',
    storageBucket: 'relive-web3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JS3Plbx7a2c7NN8B11AgJdWM67FFRtk',
    appId: '1:713602982924:android:10313c8c14f384eca0ba29',
    messagingSenderId: '713602982924',
    projectId: 'relive-web3',
    storageBucket: 'relive-web3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHWseVASx6GKsKk1bcggeJo80_uajCOx8',
    appId: '1:713602982924:ios:474cd0ba957c7261a0ba29',
    messagingSenderId: '713602982924',
    projectId: 'relive-web3',
    storageBucket: 'relive-web3.appspot.com',
    iosClientId: '713602982924-553703l0edfr94ro3m8cgunju367e3j8.apps.googleusercontent.com',
    iosBundleId: 'com.l2t.relive',
  );
}
